const UKEY="aura_users_v3",KKEY="aura_keys_v1",SESSION="aura_session",ADMIN_SESSION="aura_admin";
const ADMIN_NAME="Hoàng",ADMIN_PASSWORD="AURA_ADMIN_CHANGE_ME";
const $=id=>document.getElementById(id);
function read(k,d=[]){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function db(){return read(UKEY)}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");if(id==="admin")renderAdmin()}
function toast(t){let x=$("toast");x.textContent=t;x.style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>x.style.display="none",2300)}
function register(){let u=$("username").value.trim(),p=$("password").value;if(!u||!p)return $("authMsg").textContent="Nhập đủ thông tin.";let a=db();if(a.some(x=>x.u===u))return $("authMsg").textContent="Tên tài khoản đã tồn tại.";a.push({u,p,banned:false,lastSeen:Date.now(),created:Date.now()});write(UKEY,a);localStorage.setItem(SESSION,u);$("authMsg").textContent="Tạo tài khoản thành công.";touch();renderAdmin()}
function login(){let u=$("username").value.trim(),p=$("password").value,x=db().find(x=>x.u===u&&x.p===p);if(!x)return $("authMsg").textContent="Sai tài khoản hoặc mật khẩu.";if(x.banned)return $("authMsg").textContent="Tài khoản của bạn đã bị BAN!";localStorage.setItem(SESSION,u);touch();$("authMsg").textContent="Đăng nhập thành công.";toast("Xin chào "+u)}
function touch(){let u=localStorage.getItem(SESSION),a=db(),x=a.find(x=>x.u===u);if(x){x.lastSeen=Date.now();write(UKEY,a)}}
function onlineCount(){let now=Date.now(),a=db().filter(x=>!x.banned&&now-(x.lastSeen||0)<90000).length;$("onlineCount").textContent=a;$("statOnline").textContent=a}
function claimKey(){let u=localStorage.getItem(SESSION);if(!u){show("auth");return}touch();let x=db().find(x=>x.u===u);if(!x||x.banned)return alert("Tài khoản của bạn đã bị BAN!");let today=new Date().toISOString().slice(0,10),keys=read(KKEY),available=keys.filter(k=>k.date===today&&k.active&&k.used<(k.limit||1));let chosen=available[0];if(!chosen)return alert("Hôm nay chưa có KEY hoặc KEY đã hết lượt.");chosen.used++;write(KKEY,keys);$("keyBox").textContent=chosen.key;$("keyBox").classList.remove("hidden");navigator.clipboard?.writeText(chosen.key).catch(()=>{});renderAdmin();toast("KEY hôm nay đã được cấp • đã copy")}
function adminLogin(){if($("adminPass").value!==ADMIN_PASSWORD)return toast("Sai mật khẩu Admin");localStorage.setItem(ADMIN_SESSION,"1");renderAdmin();toast("Đăng nhập Admin thành công")}
function addKey(){if(localStorage.getItem(ADMIN_SESSION)!=="1")return toast("Cần đăng nhập Admin");let key=$("newKey").value.trim(),date=$("keyDate").value,limit=Math.max(1,Number($("keyLimit").value)||1);if(!key||!date)return toast("Nhập KEY và ngày");let a=read(KKEY);if(a.some(x=>x.key===key))return toast("KEY đã tồn tại");a.push({key,date,limit,used:0,active:true,created:Date.now()});write(KKEY,a);$("newKey").value="";$("keyLimit").value="";renderAdmin();toast("Đã thêm KEY")}
function toggleKey(i){let a=read(KKEY);if(!a[i])return;a[i].active=!a[i].active;write(KKEY,a);renderAdmin()}
function toggleBan(v){if(localStorage.getItem(ADMIN_SESSION)!=="1")return;let u=decodeURIComponent(v),a=db(),x=a.find(x=>x.u===u);if(x){x.banned=!x.banned;write(UKEY,a);renderAdmin();toast(x.banned?"Đã BAN "+u:"Đã gỡ BAN "+u)}}
function renderAdmin(){let ok=localStorage.getItem(ADMIN_SESSION)==="1";$("adminLogin").classList.toggle("hidden",ok);$("adminPanel").classList.toggle("hidden",!ok);if(!ok)return;let a=db(),keys=read(KKEY);$("statUsers").textContent=a.length;$("statBanned").textContent=a.filter(x=>x.banned).length;$("statKeys").textContent=keys.length;onlineCount();$("users").innerHTML=a.length?a.map(x=>`<div class="user"><span>${x.u}${x.banned?" — <b>ĐÃ BAN</b>":""}</span><button class="${x.banned?"":"ban"}" onclick="toggleBan('${encodeURIComponent(x.u)}')">${x.banned?"GỠ BAN":"BAN"}</button></div>`).join(""):"Chưa có tài khoản.";$("keyList").innerHTML=keys.length?keys.map((x,i)=>`<div class="keyitem"><div><b>${x.key}</b><br><small>${x.date} • ${x.used}/${x.limit} lượt • ${x.active?"ĐANG BẬT":"TẮT"}</small></div><button onclick="toggleKey(${i})">${x.active?"TẮT":"BẬT"}</button></div>`).join(""):"Chưa có KEY."}
setInterval(()=>{touch();onlineCount();if($("admin").classList.contains("active"))renderAdmin()},15000);renderAdmin();onlineCount();

// FPS-friendly particle renderer
const c=$("particles"),ctx=c.getContext("2d",{alpha:true});let W,H,DPR,pts=[],last=0,frames=0,lastAdjust=performance.now();
function resize(){DPR=Math.min(devicePixelRatio||1,1.5);W=innerWidth;H=innerHeight;c.width=W*DPR;c.height=H*DPR;c.style.width=W+"px";c.style.height=H+"px";ctx.setTransform(DPR,0,0,DPR,0,0);resetPts()}
function resetPts(){let n=Math.min(85,Math.max(28,Math.round(W*H/12000)));pts=Array.from({length:n},()=>({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.22,r:.5+Math.random()*1.4,a:.15+Math.random()*.4}))}
function frame(t){let dt=Math.min(32,t-last||16);last=t;ctx.clearRect(0,0,W,H);for(const p of pts){p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x<0)p.x=W;if(p.x>W)p.x=0;if(p.y<0)p.y=H;if(p.y>H)p.y=0;ctx.globalAlpha=p.a;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle="#b98cff";ctx.fill()}ctx.globalAlpha=1;frames++;if(t-lastAdjust>1500){let f=frames*1000/(t-lastAdjust);if(f<45&&pts.length>28)pts.length=Math.max(28,pts.length-10);else if(f>57&&pts.length<85)pts.length=Math.min(85,pts.length+5);frames=0;lastAdjust=t}requestAnimationFrame(frame)}
addEventListener("resize",resize,{passive:true});resize();requestAnimationFrame(frame);
